# Generated by Django 4.2 on 2023-04-19 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_following_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('follower', 'followed')},
        ),
    ]
