# Generated by Django 4.2 on 2023-04-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_file',
            field=models.ImageField(default=0, upload_to='tracks'),
            preserve_default=False,
        ),
    ]
