# Generated by Django 4.2 on 2023-04-07 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_track_track_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_file',
            field=models.FileField(upload_to='tracks', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
