# Generated by Django 4.2 on 2023-04-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_track_track_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='track_file',
            new_name='audio_file',
        ),
    ]
