# Generated by Django 4.2 on 2023-04-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_playlist_is_public_alter_playlist_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='api.track'),
        ),
    ]
