# Generated by Django 4.2 on 2023-04-10 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_playlist_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlydeletedplaylists',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recentlydeletedplaylists',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recentlydeletedplaylists',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='categories', to='api.playlist'),
        ),
    ]
