# Generated by Django 4.2 on 2023-04-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_recentlydeletedplaylists_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlydeletedplaylists',
            name='created_at',
            field=models.DateField(),
        ),
    ]
