# Generated by Django 4.2 on 2023-04-15 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedalbum',
            name='name',
        ),
    ]
