# Generated by Django 4.2 on 2023-04-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_likedalbum_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='recentlydeletedplaylists',
            name='is_public',
        ),
    ]
