# Generated by Django 4.2 on 2023-04-16 19:10

import auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_playlist_is_public_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth.models.UserManager()),
            ],
        ),
    ]
