# Generated by Django 4.2 on 2023-04-16 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_playlist_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlydeletedplaylists',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_playlists', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
