# Generated by Django 4.2 on 2023-04-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
