# Generated by Django 4.2 on 2023-04-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_playlist_deleted_at_playlist_is_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentlyDeletedPlaylists',
        ),
    ]
